//! The bearer token the control plane hands out, and the file it lives in.
//!
//! The control endpoints include destructive ones (delete a session, stop the VM,
//! change the LLM configuration), so they are never open: the server installs
//! [`TokenAuth`](crate::TokenAuth) unless it is started with `--no-auth`.
//!
//! The token is generated on first start, written beside the host's other data
//! (`<data-dir>/token`), and **only the account that runs the server can read
//! it** — mode `600` on Unix, an owner-only ACL on Windows. If the platform
//! cannot restrict it, the server refuses to start rather than serve a token
//! another account can read.

use std::fmt;
use std::fs::OpenOptions;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

/// Random bytes in a generated token. Hex-encoded, so 64 characters on disk.
pub const TOKEN_BYTES: usize = 32;

/// The file name, inside the host's data directory.
pub const TOKEN_FILE: &str = "token";

/// A token, and where it came from.
pub struct TokenFile {
    path: PathBuf,
    token: String,
    created: bool,
}

impl TokenFile {
    /// Where the token lives (safe to log: this is the path, not the value).
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The token itself. Never log this.
    pub fn token(&self) -> &str {
        &self.token
    }

    /// Was it generated by this call, or read back from an earlier run.
    pub fn was_created(&self) -> bool {
        self.created
    }
}

/// Why the token file could not be used.
#[derive(Debug)]
pub enum TokenError {
    /// The filesystem refused.
    Io(io::Error),
    /// The OS random source refused.
    Random(String),
    /// The file is there but empty.
    Empty,
    /// The file is not a single-line token.
    Malformed(String),
    /// The file could not be restricted to its owner.
    Permissions(String),
}

impl fmt::Display for TokenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenError::Io(e) => write!(f, "{e}"),
            TokenError::Random(e) => write!(f, "the OS random source failed: {e}"),
            TokenError::Empty => write!(
                f,
                "the token file is empty; delete it and restart to generate a new one"
            ),
            TokenError::Malformed(why) => {
                write!(f, "the token file must hold one line with no spaces: {why}")
            }
            TokenError::Permissions(why) => write!(
                f,
                "the token file could not be restricted to its owner ({why}); \
                 restricting it by hand or running with --no-auth are the options"
            ),
        }
    }
}

impl From<io::Error> for TokenError {
    fn from(error: io::Error) -> Self {
        TokenError::Io(error)
    }
}

/// Read `<data_dir>/token`, or generate one there if it does not exist yet.
///
/// An existing file is used as it stands (so an operator can provision a token
/// instead of accepting a generated one); only its shape is checked.
pub fn load_or_create(data_dir: &Path) -> Result<TokenFile, TokenError> {
    let path = data_dir.join(TOKEN_FILE);
    match std::fs::read_to_string(&path) {
        Ok(raw) => {
            let token = raw.trim().to_string();
            if token.is_empty() {
                return Err(TokenError::Empty);
            }
            if token.split_whitespace().count() != 1 {
                return Err(TokenError::Malformed("more than one word".into()));
            }
            Ok(TokenFile {
                path,
                token,
                created: false,
            })
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            std::fs::create_dir_all(data_dir)?;
            let token = generate()?;
            write_owner_only(&path, &format!("{token}\n"))?;
            Ok(TokenFile {
                path,
                token,
                created: true,
            })
        }
        Err(error) => Err(TokenError::Io(error)),
    }
}

/// 32 random bytes from the OS, as lowercase hex.
fn generate() -> Result<String, TokenError> {
    let mut bytes = [0u8; TOKEN_BYTES];
    getrandom::fill(&mut bytes).map_err(|e| TokenError::Random(e.to_string()))?;
    Ok(hex(&bytes))
}

fn hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(DIGITS[(byte >> 4) as usize] as char);
        out.push(DIGITS[(byte & 0x0f) as usize] as char);
    }
    out
}

/// Write a file only its owner can read.
fn write_owner_only(path: &Path, contents: &str) -> Result<(), TokenError> {
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        // The umask cannot loosen this: the mode is set at creation.
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = options.open(path)?;
    file.write_all(contents.as_bytes())?;
    file.sync_all()?;
    drop(file);
    #[cfg(windows)]
    restrict_to_owner(path)?;
    Ok(())
}

/// Replace the file's ACL with "the current account, full control".
///
/// Windows has no `chmod`, so the ACL is edited with `icacls` and then **read
/// back**: the file must end up with exactly one principal, the current account.
/// If that cannot be established, this fails — the server then refuses to start
/// rather than leave a token other accounts can read.
#[cfg(windows)]
fn restrict_to_owner(path: &Path) -> Result<(), TokenError> {
    let owner = current_principal()?;
    let status = std::process::Command::new("icacls")
        .arg(path)
        .arg("/inheritance:r")
        .arg("/grant:r")
        .arg(format!("{owner}:F"))
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_err(|e| TokenError::Permissions(format!("could not run icacls: {e}")))?;
    if !status.success() {
        return Err(TokenError::Permissions(
            "icacls could not set the owner-only ACL".into(),
        ));
    }
    let listing = std::process::Command::new("icacls")
        .arg(path)
        .output()
        .map_err(|e| TokenError::Permissions(format!("could not read the ACL back: {e}")))?;
    let text = String::from_utf8_lossy(&listing.stdout);
    let principals = acl_principals(&text);
    if principals.len() != 1 || principals[0] != owner {
        return Err(TokenError::Permissions(format!(
            "the ACL still lists {principals:?}"
        )));
    }
    Ok(())
}

/// The principals in an `icacls <file>` listing: the tokens that carry an
/// `(…F…)`-style rights group.
#[cfg(windows)]
fn acl_principals(listing: &str) -> Vec<String> {
    let mut principals = Vec::new();
    for token in listing.split_whitespace() {
        if let Some((principal, _)) = token.split_once(":(") {
            // The listing's first column is the path, which never contains ":(".
            let principal = principal.trim_start_matches(|c: char| c.is_whitespace());
            if !principal.is_empty() {
                principals.push(principal.to_string());
            }
        }
    }
    principals
}

/// `DOMAIN\user` of the account running this process.
#[cfg(windows)]
fn current_principal() -> Result<String, TokenError> {
    if let (Ok(domain), Ok(user)) = (std::env::var("USERDOMAIN"), std::env::var("USERNAME")) {
        if !domain.trim().is_empty() && !user.trim().is_empty() {
            return Ok(format!("{}\\{}", domain.trim(), user.trim()));
        }
    }
    let output = std::process::Command::new("whoami")
        .output()
        .map_err(|e| TokenError::Permissions(format!("could not run whoami: {e}")))?;
    let who = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if who.is_empty() {
        return Err(TokenError::Permissions("whoami printed nothing".into()));
    }
    Ok(who)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_dir(tag: &str) -> PathBuf {
        // A library test cannot use `CARGO_TARGET_TMPDIR`; a per-run directory
        // under the system temp is enough, and unique per process.
        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir = std::env::temp_dir().join(format!(
            "riscdom-token-{tag}-{}-{unique}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("scratch dir");
        dir
    }

    #[test]
    fn the_first_start_generates_a_token_and_later_ones_read_it_back() {
        let dir = scratch_dir("first");
        let created = load_or_create(&dir).expect("generate");
        assert!(created.was_created());
        assert_eq!(created.token().len(), TOKEN_BYTES * 2);
        assert!(created.token().chars().all(|c| c.is_ascii_hexdigit()));
        assert_eq!(created.path(), dir.join(TOKEN_FILE));

        let again = load_or_create(&dir).expect("read back");
        assert!(!again.was_created());
        assert_eq!(again.token(), created.token(), "the token is stable");
    }

    #[test]
    fn the_token_file_is_readable_only_by_its_owner() {
        let dir = scratch_dir("permissions");
        let token = load_or_create(&dir).expect("generate");
        let metadata = std::fs::metadata(token.path()).expect("metadata");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(metadata.permissions().mode() & 0o777, 0o600);
        }
        #[cfg(windows)]
        {
            let listing = std::process::Command::new("icacls")
                .arg(token.path())
                .output()
                .expect("icacls");
            let principals = acl_principals(&String::from_utf8_lossy(&listing.stdout));
            assert_eq!(principals.len(), 1, "one principal: {principals:?}");
            assert_eq!(principals[0], current_principal().expect("owner"));
        }
        let _ = metadata;
    }

    #[test]
    fn a_provisioned_token_is_used_as_it_stands() {
        let dir = scratch_dir("provisioned");
        std::fs::write(dir.join(TOKEN_FILE), "an-operator-made-this\n").expect("write");
        let token = load_or_create(&dir).expect("load");
        assert!(!token.was_created());
        assert_eq!(token.token(), "an-operator-made-this");
    }

    #[test]
    fn an_empty_or_multiline_file_is_refused() {
        let dir = scratch_dir("broken");
        std::fs::write(dir.join(TOKEN_FILE), "  \n").expect("write");
        assert!(matches!(
            load_or_create(&dir).err().expect("empty"),
            TokenError::Empty
        ));
        std::fs::write(dir.join(TOKEN_FILE), "two words\n").expect("write");
        assert!(matches!(
            load_or_create(&dir).err().expect("two words"),
            TokenError::Malformed(_)
        ));
    }
}
